using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CasaDiFratelli.Api.Migrations
{
    /// <inheritdoc />
    [Migration("20260610150000_AddInventoryModule")]
    public partial class AddInventoryModule : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "DiningOrders"
                ADD COLUMN IF NOT EXISTS "InventoryConsumedAtUtc" timestamp with time zone NULL;

                CREATE TABLE IF NOT EXISTS "InventoryItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" varchar(160) NOT NULL DEFAULT '',
                    "Category" varchar(80) NOT NULL DEFAULT '',
                    "Unit" varchar(20) NOT NULL DEFAULT 'g',
                    "CurrentQuantity" numeric NOT NULL DEFAULT 0,
                    "MinimumQuantity" numeric NOT NULL DEFAULT 0,
                    "UnitCost" numeric NOT NULL DEFAULT 0,
                    "IsActive" boolean NOT NULL DEFAULT true,
                    "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now(),
                    "UpdatedAtUtc" timestamp with time zone NULL,
                    CONSTRAINT "PK_InventoryItems" PRIMARY KEY ("Id")
                );
                CREATE INDEX IF NOT EXISTS "IX_InventoryItems_Name" ON "InventoryItems" ("Name");

                CREATE TABLE IF NOT EXISTS "MenuItemRecipeIngredients" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "MenuItemId" integer NOT NULL,
                    "InventoryItemId" integer NOT NULL,
                    "Quantity" numeric NOT NULL DEFAULT 0,
                    "Notes" varchar(300) NULL,
                    CONSTRAINT "PK_MenuItemRecipeIngredients" PRIMARY KEY ("Id")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_MenuItemRecipeIngredients_MenuItemId_InventoryItemId"
                ON "MenuItemRecipeIngredients" ("MenuItemId", "InventoryItemId");

                CREATE TABLE IF NOT EXISTS "DiningOrderItemInventoryExtras" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "DiningOrderItemId" integer NOT NULL,
                    "InventoryItemId" integer NOT NULL,
                    "Quantity" numeric NOT NULL DEFAULT 0,
                    "Notes" varchar(300) NULL,
                    CONSTRAINT "PK_DiningOrderItemInventoryExtras" PRIMARY KEY ("Id")
                );
                CREATE INDEX IF NOT EXISTS "IX_DiningOrderItemInventoryExtras_DiningOrderItemId"
                ON "DiningOrderItemInventoryExtras" ("DiningOrderItemId");

                CREATE TABLE IF NOT EXISTS "InventoryMovements" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "InventoryItemId" integer NOT NULL,
                    "Quantity" numeric NOT NULL DEFAULT 0,
                    "Type" varchar(40) NOT NULL DEFAULT 'ManualAdjustment',
                    "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now(),
                    "AdminUserId" integer NULL,
                    "AdminName" varchar(120) NULL,
                    "Comment" text NULL,
                    "DiningOrderId" integer NULL,
                    "DiningOrderItemId" integer NULL,
                    "InventoryAuditId" integer NULL,
                    CONSTRAINT "PK_InventoryMovements" PRIMARY KEY ("Id")
                );
                CREATE INDEX IF NOT EXISTS "IX_InventoryMovements_InventoryItemId"
                ON "InventoryMovements" ("InventoryItemId");
                CREATE INDEX IF NOT EXISTS "IX_InventoryMovements_DiningOrderId"
                ON "InventoryMovements" ("DiningOrderId");

                CREATE TABLE IF NOT EXISTS "InventoryAudits" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Title" varchar(180) NOT NULL DEFAULT '',
                    "Status" varchar(30) NOT NULL DEFAULT 'Draft',
                    "CreatedByAdminUserId" integer NULL,
                    "CreatedByAdminName" varchar(120) NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now(),
                    "ConfirmedAtUtc" timestamp with time zone NULL,
                    "ConfirmedByAdminUserId" integer NULL,
                    "ConfirmedByAdminName" varchar(120) NULL,
                    CONSTRAINT "PK_InventoryAudits" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "InventoryAuditLines" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "InventoryAuditId" integer NOT NULL,
                    "InventoryItemId" integer NOT NULL,
                    "ExpectedQuantity" numeric NOT NULL DEFAULT 0,
                    "ActualQuantity" numeric NOT NULL DEFAULT 0,
                    "DifferenceQuantity" numeric NOT NULL DEFAULT 0,
                    "Comment" varchar(300) NULL,
                    CONSTRAINT "PK_InventoryAuditLines" PRIMARY KEY ("Id")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_InventoryAuditLines_InventoryAuditId_InventoryItemId"
                ON "InventoryAuditLines" ("InventoryAuditId", "InventoryItemId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "DiningOrderItemInventoryExtras";
                DROP TABLE IF EXISTS "MenuItemRecipeIngredients";
                DROP TABLE IF EXISTS "InventoryAuditLines";
                DROP TABLE IF EXISTS "InventoryMovements";
                DROP TABLE IF EXISTS "InventoryAudits";
                DROP TABLE IF EXISTS "InventoryItems";
                ALTER TABLE "DiningOrders" DROP COLUMN IF EXISTS "InventoryConsumedAtUtc";
                """);
        }
    }
}
