using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CasaDiFratelli.Api.Migrations
{
    /// <inheritdoc />
    [Migration("20260617110000_AddMarketingCampaignSettings")]
    public partial class AddMarketingCampaignSettings : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "AppSettings" ALTER COLUMN "Value" TYPE text;

                CREATE TABLE IF NOT EXISTS "MarketingMessageLogs" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CampaignKey" varchar(80) NOT NULL,
                    "CustomerKey" varchar(180) NOT NULL,
                    "Email" varchar(180) NOT NULL,
                    "SentForDate" date NOT NULL,
                    "SentAtUtc" timestamp with time zone NOT NULL DEFAULT now(),
                    "Subject" varchar(220) NOT NULL,
                    "DiscountPercent" numeric NOT NULL DEFAULT 0,
                    CONSTRAINT "PK_MarketingMessageLogs" PRIMARY KEY ("Id")
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_MarketingMessageLogs_CampaignKey_CustomerKey_SentForDate"
                ON "MarketingMessageLogs" ("CampaignKey", "CustomerKey", "SentForDate");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP INDEX IF EXISTS "IX_MarketingMessageLogs_CampaignKey_CustomerKey_SentForDate";
                DROP TABLE IF EXISTS "MarketingMessageLogs";
                """);
        }
    }
}
