using CasaDiFratelli.Api.Data;
using CasaDiFratelli.Api.Filters;
using CasaDiFratelli.Api.Models;
using CasaDiFratelli.Api.Services;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CasaDiFratelli.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public class MenuController : ControllerBase
{
    private const int MaxInlineImageLength = 900_000;
    private readonly AppDbContext _db;
    private readonly EmailService _emailService;
    private readonly ILogger<MenuController> _logger;
    private readonly AuditService _audit;

    public MenuController(
        AppDbContext db,
        EmailService emailService,
        ILogger<MenuController> logger,
        AuditService audit)
    {
        _db = db;
        _emailService = emailService;
        _logger = logger;
        _audit = audit;
    }

    private static void AddParameter(IDbCommand command, string name, object? value)
    {
        var parameter = command.CreateParameter();
        parameter.ParameterName = name;
        parameter.Value = value ?? DBNull.Value;
        command.Parameters.Add(parameter);
    }

    private static object? ToAuditSnapshot(MenuItem? item)
    {
        if (item == null) return null;

        return new
        {
            item.Id,
            item.NameBg,
            item.NameEn,
            item.DescriptionBg,
            item.DescriptionEn,
            HasImage = !string.IsNullOrWhiteSpace(item.ImageUrl),
            ImageUrlLength = item.ImageUrl?.Length ?? 0,
            item.Weight,
            item.Price,
            item.Category,
            item.IsActive,
            item.NotifySubscribers
        };
    }

    private static string NormalizeImageUrl(string? imageUrl)
    {
        return imageUrl?.Trim() ?? string.Empty;
    }

    private static bool IsImageUrlTooLarge(string imageUrl)
    {
        return imageUrl.StartsWith("data:", StringComparison.OrdinalIgnoreCase) &&
            imageUrl.Length > MaxInlineImageLength;
    }

    private async Task EnsureConnectionOpenAsync()
    {
        var connection = _db.Database.GetDbConnection();

        if (connection.State != ConnectionState.Open)
        {
            await connection.OpenAsync();
        }
    }

    private async Task EnsureMenuStorageAsync()
    {
        await EnsureConnectionOpenAsync();

        await using var command = _db.Database.GetDbConnection().CreateCommand();
        command.CommandText = """
            CREATE TABLE IF NOT EXISTS "MenuItems" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "NameBg" text NOT NULL DEFAULT '',
                "NameEn" text NOT NULL DEFAULT '',
                "DescriptionBg" text NOT NULL DEFAULT '',
                "DescriptionEn" text NOT NULL DEFAULT '',
                "ImageUrl" text NOT NULL DEFAULT '',
                "Weight" text NOT NULL DEFAULT '',
                "Price" numeric NOT NULL DEFAULT 0,
                "Category" text NOT NULL DEFAULT 'main',
                "IsActive" boolean NOT NULL DEFAULT true,
                "NotifySubscribers" boolean NOT NULL DEFAULT false,
                "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now(),
                "UpdatedAtUtc" timestamp with time zone NULL,
                CONSTRAINT "PK_MenuItems" PRIMARY KEY ("Id")
            );

            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "NameBg" text NOT NULL DEFAULT '';
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "NameEn" text NOT NULL DEFAULT '';
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "DescriptionBg" text NOT NULL DEFAULT '';
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "DescriptionEn" text NOT NULL DEFAULT '';
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "ImageUrl" text NOT NULL DEFAULT '';
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "Weight" text NOT NULL DEFAULT '';
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "Price" numeric NOT NULL DEFAULT 0;
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "Category" text NOT NULL DEFAULT 'main';
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "IsActive" boolean NOT NULL DEFAULT true;
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "NotifySubscribers" boolean NOT NULL DEFAULT false;
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now();
            ALTER TABLE "MenuItems" ADD COLUMN IF NOT EXISTS "UpdatedAtUtc" timestamp with time zone NULL;
            """;

        await command.ExecuteNonQueryAsync();
    }

    private static bool ReadBoolean(IDataRecord reader, int index, bool fallback = false)
    {
        if (reader.IsDBNull(index)) return fallback;

        var value = reader.GetValue(index);
        return value switch
        {
            bool boolValue => boolValue,
            int intValue => intValue != 0,
            long longValue => longValue != 0,
            short shortValue => shortValue != 0,
            string stringValue => stringValue.Equals("true", StringComparison.OrdinalIgnoreCase) || stringValue == "1",
            _ => Convert.ToBoolean(value)
        };
    }

    private async Task<List<object>> ReadMenuItemsAsync()
    {
        await EnsureConnectionOpenAsync();

        await using var command = _db.Database.GetDbConnection().CreateCommand();
        command.CommandText = """
            SELECT
                "Id",
                "NameBg",
                "NameEn",
                "DescriptionBg",
                "DescriptionEn",
                "ImageUrl",
                "Weight",
                "Price",
                "Category",
                "IsActive",
                "NotifySubscribers"
            FROM "MenuItems"
            ORDER BY "Category", "NameBg";
            """;

        var items = new List<object>();
        await using var reader = await command.ExecuteReaderAsync();

        while (await reader.ReadAsync())
        {
            items.Add(new
            {
                Id = reader.GetInt32(0),
                NameBg = reader.IsDBNull(1) ? string.Empty : reader.GetString(1),
                NameEn = reader.IsDBNull(2) ? string.Empty : reader.GetString(2),
                DescriptionBg = reader.IsDBNull(3) ? string.Empty : reader.GetString(3),
                DescriptionEn = reader.IsDBNull(4) ? string.Empty : reader.GetString(4),
                ImageUrl = reader.IsDBNull(5) ? string.Empty : reader.GetString(5),
                Weight = reader.IsDBNull(6) ? string.Empty : reader.GetString(6),
                Price = reader.IsDBNull(7) ? 0m : Convert.ToDecimal(reader.GetValue(7)),
                Category = reader.IsDBNull(8) ? "main" : reader.GetString(8),
                IsActive = ReadBoolean(reader, 9, true),
                NotifySubscribers = ReadBoolean(reader, 10)
            });
        }

        return items;
    }

    [HttpGet]
    public async Task<IActionResult> Get()
    {
        try
        {
            await EnsureMenuStorageAsync();

            var items = await ReadMenuItemsAsync();

            return Ok(items);
        }
        catch (Exception error)
        {
            _logger.LogError(error, "Failed to load menu items.");
            return StatusCode(500, new { message = "Failed to load menu items.", detail = error.Message });
        }
    }

    [HttpPost("seed")]
    [AdminAuthorize]
    public async Task<IActionResult> Seed()
    {
        try
        {
            await EnsureMenuStorageAsync();
            var created = await MenuSeedData.SeedAsync(_db);
            var total = await _db.MenuItems.CountAsync();

            return Ok(new
            {
                Created = created,
                Total = total
            });
        }
        catch (Exception error)
        {
            _logger.LogError(error, "Failed to seed menu items.");
            return StatusCode(500, new { message = "Failed to seed menu items." });
        }
    }

    [HttpPost]
    [AdminAuthorize]
    public async Task<IActionResult> Create([FromBody] MenuItem item)
    {
        try
        {
            await AdminSchemaBootstrapper.EnsureAsync(_db);

            if (string.IsNullOrWhiteSpace(item.NameBg))
                return BadRequest(new { message = "Dish name is required." });

            if (item.Price <= 0)
                return BadRequest(new { message = "Dish price must be greater than zero." });

            item.NameBg = item.NameBg.Trim();
            item.NameEn = string.IsNullOrWhiteSpace(item.NameEn) ? item.NameBg : item.NameEn.Trim();
            item.DescriptionBg = item.DescriptionBg?.Trim() ?? string.Empty;
            item.DescriptionEn = item.DescriptionEn?.Trim() ?? string.Empty;
            item.ImageUrl = NormalizeImageUrl(item.ImageUrl);
            if (IsImageUrlTooLarge(item.ImageUrl))
                return BadRequest(new { message = "Dish photo is too large. Please upload a smaller image." });
            item.Weight = item.Weight?.Trim() ?? string.Empty;
            item.Category = string.IsNullOrWhiteSpace(item.Category) ? "main" : item.Category.Trim();
            item.CreatedAtUtc = DateTime.UtcNow;

            await using var command = _db.Database.GetDbConnection().CreateCommand();
            command.CommandText = """
                INSERT INTO "MenuItems"
                ("NameBg", "NameEn", "DescriptionBg", "DescriptionEn", "ImageUrl", "Weight", "Price", "Category", "IsActive", "NotifySubscribers", "CreatedAtUtc")
                VALUES
                (@nameBg, @nameEn, @descriptionBg, @descriptionEn, @imageUrl, @weight, @price, @category, @isActive, @notifySubscribers, now())
                RETURNING "Id";
                """;
            AddParameter(command, "@nameBg", item.NameBg);
            AddParameter(command, "@nameEn", item.NameEn);
            AddParameter(command, "@descriptionBg", item.DescriptionBg);
            AddParameter(command, "@descriptionEn", item.DescriptionEn);
            AddParameter(command, "@imageUrl", item.ImageUrl);
            AddParameter(command, "@weight", item.Weight);
            AddParameter(command, "@price", item.Price);
            AddParameter(command, "@category", item.Category);
            AddParameter(command, "@isActive", item.IsActive);
            AddParameter(command, "@notifySubscribers", item.NotifySubscribers);

            item.Id = Convert.ToInt32(await command.ExecuteScalarAsync());
            await _audit.RecordAsync(HttpContext, "create", "MenuItem", item.Id.ToString(), after: ToAuditSnapshot(item));

            if (item.NotifySubscribers)
            {
                var subscribers = await _db.CustomerProfiles
                    .Where(x => x.MarketingConsent && !string.IsNullOrWhiteSpace(x.Email))
                    .ToListAsync();

                foreach (var customer in subscribers)
                {
                    try
                    {
                        await _emailService.SendAsync(
                            customer.Email!,
                            $"Ново предложение · Casa di Fratelli",
                            $"""
                            <div style="font-family:Arial,sans-serif">
                                <h2>{item.NameBg}</h2>
                                <p>{item.DescriptionBg}</p>

                                <p>
                                    <strong>{item.Weight}</strong>
                                    ·
                                    <strong>€{item.Price:F2}</strong>
                                </p>

                                <p>
                                    Очакваме Ви в Casa di Fratelli.
                                </p>
                            </div>
                            """
                        );
                    }
                    catch
                    {
                    }
                }
            }

            return Ok(new
            {
                item.Id,
                item.NameBg,
                item.NameEn,
                item.DescriptionBg,
                item.DescriptionEn,
                item.ImageUrl,
                item.Weight,
                item.Price,
                item.Category,
                item.IsActive,
                item.NotifySubscribers
            });
        }
        catch (Exception error)
        {
            _logger.LogError(error, "Failed to create menu item.");
            return StatusCode(500, new { message = "Failed to create menu item." });
        }
    }

    [HttpPut("{id}")]
    [AdminAuthorize]
    public async Task<IActionResult> Update(int id, [FromBody] MenuItem updated)
    {
        try
        {
            await AdminSchemaBootstrapper.EnsureAsync(_db);
            await EnsureMenuStorageAsync();

            var imageUrl = NormalizeImageUrl(updated.ImageUrl);
            if (IsImageUrlTooLarge(imageUrl))
                return BadRequest(new { message = "Dish photo is too large. Please upload a smaller image." });

            updated.NameBg = updated.NameBg?.Trim() ?? string.Empty;
            updated.NameEn = string.IsNullOrWhiteSpace(updated.NameEn) ? updated.NameBg : updated.NameEn.Trim();
            updated.DescriptionBg = updated.DescriptionBg?.Trim() ?? string.Empty;
            updated.DescriptionEn = updated.DescriptionEn?.Trim() ?? string.Empty;
            updated.ImageUrl = imageUrl;
            updated.Weight = updated.Weight?.Trim() ?? string.Empty;
            updated.Category = string.IsNullOrWhiteSpace(updated.Category) ? "main" : updated.Category.Trim();

            var before = await _db.MenuItems.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);
            await using var command = _db.Database.GetDbConnection().CreateCommand();
            command.CommandText = """
                UPDATE "MenuItems"
                SET
                    "NameBg" = @nameBg,
                    "NameEn" = @nameEn,
                    "DescriptionBg" = @descriptionBg,
                    "DescriptionEn" = @descriptionEn,
                    "ImageUrl" = @imageUrl,
                    "Weight" = @weight,
                    "Price" = @price,
                    "Category" = @category,
                    "IsActive" = @isActive,
                    "NotifySubscribers" = @notifySubscribers,
                    "UpdatedAtUtc" = now()
                WHERE "Id" = @id;
                """;
            AddParameter(command, "@id", id);
            AddParameter(command, "@nameBg", updated.NameBg);
            AddParameter(command, "@nameEn", updated.NameEn);
            AddParameter(command, "@descriptionBg", updated.DescriptionBg);
            AddParameter(command, "@descriptionEn", updated.DescriptionEn);
            AddParameter(command, "@imageUrl", updated.ImageUrl);
            AddParameter(command, "@weight", updated.Weight);
            AddParameter(command, "@price", updated.Price);
            AddParameter(command, "@category", updated.Category);
            AddParameter(command, "@isActive", updated.IsActive);
            AddParameter(command, "@notifySubscribers", updated.NotifySubscribers);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows == 0)
                return NotFound();

            await _audit.RecordAsync(HttpContext, "update", "MenuItem", id.ToString(), ToAuditSnapshot(before), ToAuditSnapshot(updated));

            return Ok(new
            {
                Id = id,
                updated.NameBg,
                updated.NameEn,
                updated.DescriptionBg,
                updated.DescriptionEn,
                updated.ImageUrl,
                updated.Weight,
                updated.Price,
                updated.Category,
                updated.IsActive,
                updated.NotifySubscribers
            });
        }
        catch (Exception error)
        {
            _logger.LogError(error, "Failed to update menu item {MenuItemId}.", id);
            return StatusCode(500, new { message = "Failed to update menu item.", detail = error.Message });
        }
    }

    [HttpDelete("{id}")]
    [AdminAuthorize]
    public async Task<IActionResult> Delete(int id)
    {
        await EnsureMenuStorageAsync();

        var before = await _db.MenuItems.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);
        await using var command = _db.Database.GetDbConnection().CreateCommand();
        command.CommandText = """
            DELETE FROM "MenuItems"
            WHERE "Id" = @id;
            """;
        AddParameter(command, "@id", id);

        var affectedRows = await command.ExecuteNonQueryAsync();
        if (affectedRows == 0)
            return NotFound();

        await _audit.RecordAsync(HttpContext, "delete", "MenuItem", id.ToString(), ToAuditSnapshot(before));

        return Ok();
    }
}
